<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Profile\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Profile\AuthorizedApp;
use Linode\Profile\AuthorizedAppRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class AuthorizedAppRepository extends AbstractRepository implements AuthorizedAppRepositoryInterface
{
    public function deleteProfileApp(int $appId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $appId));
    }

    protected function getBaseUri(): string
    {
        return '/profile/apps';
    }

    protected function getSupportedFields(): array
    {
        return [
            AuthorizedApp::FIELD_ID,
            AuthorizedApp::FIELD_LABEL,
            AuthorizedApp::FIELD_SCOPES,
            AuthorizedApp::FIELD_WEBSITE,
            AuthorizedApp::FIELD_CREATED,
            AuthorizedApp::FIELD_EXPIRY,
            AuthorizedApp::FIELD_THUMBNAIL_URL,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new AuthorizedApp($this->client, $json);
    }
}
