<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Profile\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Profile\PersonalAccessToken;
use Linode\Profile\PersonalAccessTokenRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class PersonalAccessTokenRepository extends AbstractRepository implements PersonalAccessTokenRepositoryInterface
{
    public function create(array $parameters): PersonalAccessToken
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new PersonalAccessToken($this->client, $json);
    }

    public function update(int $id, array $parameters): PersonalAccessToken
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new PersonalAccessToken($this->client, $json);
    }

    public function revoke(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return '/profile/tokens';
    }

    protected function getSupportedFields(): array
    {
        return [
            PersonalAccessToken::FIELD_ID,
            PersonalAccessToken::FIELD_LABEL,
            PersonalAccessToken::FIELD_SCOPES,
            PersonalAccessToken::FIELD_CREATED,
            PersonalAccessToken::FIELD_TOKEN,
            PersonalAccessToken::FIELD_EXPIRY,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new PersonalAccessToken($this->client, $json);
    }
}
