<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Profile\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Profile\SSHKey;
use Linode\Profile\SSHKeyRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class SSHKeyRepository extends AbstractRepository implements SSHKeyRepositoryInterface
{
    public function add(array $parameters): SSHKey
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new SSHKey($this->client, $json);
    }

    public function update(int $id, array $parameters): SSHKey
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new SSHKey($this->client, $json);
    }

    public function delete(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return '/profile/sshkeys';
    }

    protected function getSupportedFields(): array
    {
        return [
            SSHKey::FIELD_ID,
            SSHKey::FIELD_LABEL,
            SSHKey::FIELD_SSH_KEY,
            SSHKey::FIELD_CREATED,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new SSHKey($this->client, $json);
    }
}
