<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Profile\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Profile\SSHKey;
use Linode\Profile\SSHKeyRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class SSHKeyRepository extends AbstractRepository implements SSHKeyRepositoryInterface
{
    public function addSSHKey(array $parameters = []): SSHKey
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new SSHKey($this->client, $json);
    }

    public function updateSSHKey(int $sshKeyId, array $parameters = []): SSHKey
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $sshKeyId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new SSHKey($this->client, $json);
    }

    public function deleteSSHKey(int $sshKeyId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $sshKeyId));
    }

    protected function getBaseUri(): string
    {
        return '/profile/sshkeys';
    }

    protected function getSupportedFields(): array
    {
        return [
            SSHKey::FIELD_ID,
            SSHKey::FIELD_LABEL,
            SSHKey::FIELD_SSH_KEY,
            SSHKey::FIELD_CREATED,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new SSHKey($this->client, $json);
    }
}
