<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Profile\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Profile\TrustedDevice;
use Linode\Profile\TrustedDeviceRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class TrustedDeviceRepository extends AbstractRepository implements TrustedDeviceRepositoryInterface
{
    public function revokeTrustedDevice(int $deviceId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $deviceId));
    }

    protected function getBaseUri(): string
    {
        return '/profile/devices';
    }

    protected function getSupportedFields(): array
    {
        return [
            TrustedDevice::FIELD_ID,
            TrustedDevice::FIELD_CREATED,
            TrustedDevice::FIELD_EXPIRY,
            TrustedDevice::FIELD_USER_AGENT,
            TrustedDevice::FIELD_LAST_AUTHENTICATED,
            TrustedDevice::FIELD_LAST_REMOTE_ADDR,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new TrustedDevice($this->client, $json);
    }
}
