<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Tags;

use Linode\Entity;
use Linode\Tags\Repository\TaggedObjectRepository;

/**
 * A tag that has been applied to an object on your Account. Tags are
 * currently for organizational purposes only.
 *
 * @property string                          $label   A Label used for organization of objects on your Account.
 * @property TaggedObjectRepositoryInterface $objects Tagged objects.
 */
class Tag extends Entity
{
    // Available fields.
    public const FIELD_LABEL          = 'label';
    public const FIELD_LINODES        = 'linodes';
    public const FIELD_DOMAINS        = 'domains';
    public const FIELD_VOLUMES        = 'volumes';
    public const FIELD_NODE_BALANCERS = 'nodebalancers';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            'objects' => new TaggedObjectRepository($this->client, $this->label),
            default   => parent::__get($name),
        };
    }
}
