<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Networking\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Networking\Firewall;
use Linode\Networking\FirewallRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class FirewallRepository extends AbstractRepository implements FirewallRepositoryInterface
{
    public function createFirewalls(array $parameters = []): Firewall
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Firewall($this->client, $json);
    }

    public function updateFirewall(int $firewallId, array $parameters = []): Firewall
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $firewallId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Firewall($this->client, $json);
    }

    public function deleteFirewall(int $firewallId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $firewallId));
    }

    protected function getBaseUri(): string
    {
        return 'beta/networking/firewalls';
    }

    protected function getSupportedFields(): array
    {
        return [
            Firewall::FIELD_ID,
            Firewall::FIELD_LABEL,
            Firewall::FIELD_STATUS,
            Firewall::FIELD_CREATED,
            Firewall::FIELD_UPDATED,
            Firewall::FIELD_RULES,
            Firewall::FIELD_TAGS,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Firewall($this->client, $json);
    }
}
