<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Networking\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Networking\Vlans;
use Linode\Networking\VlansRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class VlansRepository extends AbstractRepository implements VlansRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return 'beta/networking/vlans';
    }

    protected function getSupportedFields(): array
    {
        return [
            Vlans::FIELD_REGION,
            Vlans::FIELD_LABEL,
            Vlans::FIELD_LINODES,
            Vlans::FIELD_CREATED,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Vlans($this->client, $json);
    }
}
