<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Longview\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Longview\LongviewClient;
use Linode\Longview\LongviewClientRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class LongviewClientRepository extends AbstractRepository implements LongviewClientRepositoryInterface
{
    public function create(array $parameters): LongviewClient
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new LongviewClient($this->client, $json);
    }

    public function update(int $id, array $parameters): LongviewClient
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new LongviewClient($this->client, $json);
    }

    public function delete(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return '/longview/clients';
    }

    protected function getSupportedFields(): array
    {
        return [
            LongviewClient::FIELD_LABEL,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new LongviewClient($this->client, $json);
    }
}
