<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Longview\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Longview\LongviewClient;
use Linode\Longview\LongviewClientRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class LongviewClientRepository extends AbstractRepository implements LongviewClientRepositoryInterface
{
    public function createLongviewClient(array $parameters = []): LongviewClient
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new LongviewClient($this->client, $json);
    }

    public function updateLongviewClient(int $clientId, array $parameters = []): LongviewClient
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $clientId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new LongviewClient($this->client, $json);
    }

    public function deleteLongviewClient(int $clientId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $clientId));
    }

    protected function getBaseUri(): string
    {
        return '/longview/clients';
    }

    protected function getSupportedFields(): array
    {
        return [
            LongviewClient::FIELD_ID,
            LongviewClient::FIELD_LABEL,
            LongviewClient::FIELD_API_KEY,
            LongviewClient::FIELD_INSTALL_CODE,
            LongviewClient::FIELD_CREATED,
            LongviewClient::FIELD_UPDATED,
            LongviewClient::FIELD_APPS,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new LongviewClient($this->client, $json);
    }
}
