<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Longview\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Longview\LongviewSubscription;
use Linode\Longview\LongviewSubscriptionRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class LongviewSubscriptionRepository extends AbstractRepository implements LongviewSubscriptionRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return '/longview/subscriptions';
    }

    protected function getSupportedFields(): array
    {
        return [
            LongviewSubscription::FIELD_ID,
            LongviewSubscription::FIELD_LABEL,
            LongviewSubscription::FIELD_CLIENTS_INCLUDED,
            LongviewSubscription::FIELD_PRICE,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new LongviewSubscription($this->client, $json);
    }
}
