<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Managed;

use Linode\Entity;
use Linode\Linode\LinodeEntity;

/**
 * An Issue that was detected with a service Linode is managing.
 *
 * @property int          $id       This Issue's unique ID.
 * @property string       $created  When this Issue was created. Issues are created in response to issues detected
 *                                  with Managed Services, so this is also when the Issue was detected.
 * @property int[]        $services An array of Managed Service IDs that were affected by this Issue.
 * @property LinodeEntity $entity   The ticket this Managed Issue opened.
 */
class ManagedIssue extends Entity
{
    // Available fields.
    public const FIELD_ID       = 'id';
    public const FIELD_CREATED  = 'created';
    public const FIELD_SERVICES = 'services';
    public const FIELD_ENTITY   = 'entity';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_ENTITY => new LinodeEntity($this->client, $this->data[$name]),
            default            => parent::__get($name),
        };
    }
}
