<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Managed;

use Linode\Entity;

/**
 * An Issue that was detected with a service Linode is managing.
 *
 * @property int                $id       This Issue's unique ID.
 * @property string             $created  When this Issue was created. Issues are created in response to issues
 *                                        detected with Managed Services, so this is also when the Issue was
 *                                        detected.
 * @property int[]              $services An array of Managed Service IDs that were affected by this Issue.
 * @property ManagedIssueEntity $entity   The ticket this Managed Issue opened.
 */
class ManagedIssue extends Entity
{
    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            'entity' => new ManagedIssueEntity($this->client, $this->data['entity']),
            default  => parent::__get($name),
        };
    }
}
