<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Managed;

use Linode\Entity;

/**
 * A collection of graph data returned for managed stats.
 *
 * @property StatsData[] $cpu     CPU usage stats from the last 24 hours.
 * @property StatsData[] $disk    Disk usage stats from the last 24 hours.
 * @property StatsData[] $swap    Swap usage stats from the last 24 hours.
 * @property StatsData[] $net_in  Inbound network traffic stats from the last 24 hours.
 * @property StatsData[] $net_out Outbound network traffic stats from the last 24 hours.
 */
class StatsDataAvailable extends Entity
{
    // Available fields.
    public const FIELD_CPU     = 'cpu';
    public const FIELD_DISK    = 'disk';
    public const FIELD_SWAP    = 'swap';
    public const FIELD_NET_IN  = 'net_in';
    public const FIELD_NET_OUT = 'net_out';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            default => array_map(fn ($data) => new StatsData($this->client, $data), $this->data[$name]),
        };
    }
}
