<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LKE\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LKE\LKECluster;
use Linode\LKE\LKEClusterRepositoryInterface;
use Linode\LKE\LKENodeStatus;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class LKEClusterRepository extends AbstractRepository implements LKEClusterRepositoryInterface
{
    public function createLKECluster(array $parameters = []): LKECluster
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new LKECluster($this->client, $json);
    }

    public function putLKECluster(int $clusterId, array $parameters = []): LKECluster
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $clusterId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new LKECluster($this->client, $json);
    }

    public function deleteLKECluster(int $clusterId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $clusterId));
    }

    public function postLKEClusterRecycle(int $clusterId): void
    {
        $this->client->post(sprintf('%s/%s/recycle', $this->getBaseUri(), $clusterId));
    }

    public function getLKEClusterNode(int $clusterId, string $nodeId): LKENodeStatus
    {
        $response = $this->client->get(sprintf('%s/%s/nodes/%s', $this->getBaseUri(), $clusterId, $nodeId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new LKENodeStatus($this->client, $json);
    }

    public function deleteLKEClusterNode(int $clusterId, string $nodeId): void
    {
        $this->client->delete(sprintf('%s/%s/nodes/%s', $this->getBaseUri(), $clusterId, $nodeId));
    }

    public function postLKEClusterNodeRecycle(int $clusterId, string $nodeId): void
    {
        $this->client->post(sprintf('%s/%s/nodes/%s/recycle', $this->getBaseUri(), $clusterId, $nodeId));
    }

    public function getLKEClusterKubeconfig(int $clusterId): string
    {
        $response = $this->client->get(sprintf('%s/%s/kubeconfig', $this->getBaseUri(), $clusterId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return $json['kubeconfig'];
    }

    public function deleteLKEClusterKubeconfig(int $clusterId): void
    {
        $this->client->delete(sprintf('%s/%s/kubeconfig', $this->getBaseUri(), $clusterId));
    }

    protected function getBaseUri(): string
    {
        return '/lke/clusters';
    }

    protected function getSupportedFields(): array
    {
        return [
            LKECluster::FIELD_ID,
            LKECluster::FIELD_LABEL,
            LKECluster::FIELD_REGION,
            LKECluster::FIELD_CREATED,
            LKECluster::FIELD_UPDATED,
            LKECluster::FIELD_K8S_VERSION,
            LKECluster::FIELD_TAGS,
            LKECluster::FIELD_CONTROL_PLANE,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new LKECluster($this->client, $json);
    }
}
