<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LKE\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LKE\LKEVersion;
use Linode\LKE\LKEVersionRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class LKEVersionRepository extends AbstractRepository implements LKEVersionRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return 'beta/lke/versions';
    }

    protected function getSupportedFields(): array
    {
        return [
            LKEVersion::FIELD_ID,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new LKEVersion($this->client, $json);
    }
}
