<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Support\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Support\SupportTicket;
use Linode\Support\SupportTicketRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class SupportTicketRepository extends AbstractRepository implements SupportTicketRepositoryInterface
{
    public function open(array $parameters): SupportTicket
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new SupportTicket($this->client, $json);
    }

    public function close(int $id): void
    {
        $this->client->post(sprintf('%s/%s/close', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return '/support/tickets';
    }

    protected function getSupportedFields(): array
    {
        return [
            SupportTicket::FIELD_ID,
            SupportTicket::FIELD_SUMMARY,
            SupportTicket::FIELD_OPENED_BY,
            SupportTicket::FIELD_OPENED,
            SupportTicket::FIELD_DESCRIPTION,
            SupportTicket::FIELD_GRAVATAR_ID,
            SupportTicket::FIELD_STATUS,
            SupportTicket::FIELD_CLOSABLE,
            SupportTicket::FIELD_UPDATED_BY,
            SupportTicket::FIELD_UPDATED,
            SupportTicket::FIELD_CLOSED,
            SupportTicket::FIELD_DOMAIN_ID,
            SupportTicket::FIELD_LINODE_ID,
            SupportTicket::FIELD_LONGVIEWCLIENT_ID,
            SupportTicket::FIELD_NODEBALANCER_ID,
            SupportTicket::FIELD_VOLUME_ID,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new SupportTicket($this->client, $json);
    }
}
