<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Support\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Support\SupportTicket;
use Linode\Support\SupportTicketRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class SupportTicketRepository extends AbstractRepository implements SupportTicketRepositoryInterface
{
    public function createTicket(array $parameters = []): SupportTicket
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new SupportTicket($this->client, $json);
    }

    public function createTicketAttachment(int $ticketId, string $file): void
    {
        $options = [
            'multipart' => [
                'name'     => 'file',
                'contents' => fopen($file, 'r'),
            ],
        ];

        $this->client->post(sprintf('%s/%s/attachments', $this->getBaseUri(), $ticketId), [], $options);
    }

    public function closeTicket(int $ticketId): void
    {
        $this->client->post(sprintf('%s/%s/close', $this->getBaseUri(), $ticketId));
    }

    protected function getBaseUri(): string
    {
        return '/support/tickets';
    }

    protected function getSupportedFields(): array
    {
        return [
            SupportTicket::FIELD_ID,
            SupportTicket::FIELD_SUMMARY,
            SupportTicket::FIELD_OPENED_BY,
            SupportTicket::FIELD_OPENED,
            SupportTicket::FIELD_DESCRIPTION,
            SupportTicket::FIELD_ENTITY,
            SupportTicket::FIELD_GRAVATAR_ID,
            SupportTicket::FIELD_STATUS,
            SupportTicket::FIELD_CLOSABLE,
            SupportTicket::FIELD_UPDATED_BY,
            SupportTicket::FIELD_UPDATED,
            SupportTicket::FIELD_CLOSED,
            SupportTicket::FIELD_ATTACHMENTS,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new SupportTicket($this->client, $json);
    }
}
