<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Databases\Repository;

use Linode\Databases\DatabaseEngine;
use Linode\Databases\DatabaseEngineRepositoryInterface;
use Linode\Entity;
use Linode\Internal\AbstractRepository;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class DatabaseEngineRepository extends AbstractRepository implements DatabaseEngineRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return 'beta/databases/engines';
    }

    protected function getSupportedFields(): array
    {
        return [
            DatabaseEngine::FIELD_ID,
            DatabaseEngine::FIELD_ENGINE,
            DatabaseEngine::FIELD_VERSION,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new DatabaseEngine($this->client, $json);
    }
}
