<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Databases\Repository;

use Linode\Databases\DatabaseBackup;
use Linode\Databases\DatabaseCredentials;
use Linode\Databases\DatabaseMongoDB;
use Linode\Databases\DatabaseMongoDBRepositoryInterface;
use Linode\Databases\DatabaseSSL;
use Linode\Entity;
use Linode\Internal\AbstractRepository;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class DatabaseMongoDBRepository extends AbstractRepository implements DatabaseMongoDBRepositoryInterface
{
    public function putDatabasesMongoDBInstance(int $instanceId, array $parameters = []): DatabaseMongoDB
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $instanceId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabaseMongoDB($this->client, $json);
    }

    public function deleteDatabasesMongoDBInstance(int $instanceId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $instanceId));
    }

    public function getDatabasesMongoDBInstanceBackups(int $instanceId): array
    {
        $response = $this->client->get(sprintf('%s/%s/backups', $this->getBaseUri(), $instanceId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return array_map(fn ($data) => new DatabaseBackup($this->client, $data), $json['data']);
    }

    public function postDatabasesMongoDBInstanceBackup(int $instanceId, array $parameters = []): void
    {
        $this->client->post(sprintf('%s/%s/backups', $this->getBaseUri(), $instanceId), $parameters);
    }

    public function getDatabasesMongoDBInstanceBackup(int $instanceId, int $backupId): DatabaseBackup
    {
        $response = $this->client->get(sprintf('%s/%s/backups/%s', $this->getBaseUri(), $instanceId, $backupId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabaseBackup($this->client, $json);
    }

    public function deleteDatabaseMongoDBInstanceBackup(int $instanceId, int $backupId): void
    {
        $this->client->delete(sprintf('%s/%s/backups/%s', $this->getBaseUri(), $instanceId, $backupId));
    }

    public function postDatabasesMongoDBInstanceBackupRestore(int $instanceId, int $backupId): void
    {
        $this->client->post(sprintf('%s/%s/backups/%s/restore', $this->getBaseUri(), $instanceId, $backupId));
    }

    public function getDatabasesMongoDBInstanceCredentials(int $instanceId): DatabaseCredentials
    {
        $response = $this->client->get(sprintf('%s/%s/credentials', $this->getBaseUri(), $instanceId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabaseCredentials($this->client, $json);
    }

    public function postDatabasesMongoDBInstanceCredentialsReset(int $instanceId): void
    {
        $this->client->post(sprintf('%s/%s/credentials/reset', $this->getBaseUri(), $instanceId));
    }

    public function getDatabasesMongoDBInstanceSSL(int $instanceId): DatabaseSSL
    {
        $response = $this->client->get(sprintf('%s/%s/ssl', $this->getBaseUri(), $instanceId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabaseSSL($this->client, $json);
    }

    public function postDatabasesMongoDBInstancePatch(int $instanceId): void
    {
        $this->client->post(sprintf('%s/%s/patch', $this->getBaseUri(), $instanceId));
    }

    protected function getBaseUri(): string
    {
        return 'beta/databases/mongodb/instances';
    }

    protected function getSupportedFields(): array
    {
        return [
            DatabaseMongoDB::FIELD_ID,
            DatabaseMongoDB::FIELD_LABEL,
            DatabaseMongoDB::FIELD_REGION,
            DatabaseMongoDB::FIELD_TYPE,
            DatabaseMongoDB::FIELD_CLUSTER_SIZE,
            DatabaseMongoDB::FIELD_ENGINE,
            DatabaseMongoDB::FIELD_VERSION,
            DatabaseMongoDB::FIELD_PORT,
            DatabaseMongoDB::FIELD_COMPRESSION_TYPE,
            DatabaseMongoDB::FIELD_STATUS,
            DatabaseMongoDB::FIELD_ENCRYPTED,
            DatabaseMongoDB::FIELD_ALLOW_LIST,
            DatabaseMongoDB::FIELD_HOSTS,
            DatabaseMongoDB::FIELD_PEERS,
            DatabaseMongoDB::FIELD_REPLICA_SET,
            DatabaseMongoDB::FIELD_SSL_CONNECTION,
            DatabaseMongoDB::FIELD_STORAGE_ENGINE,
            DatabaseMongoDB::FIELD_CREATED,
            DatabaseMongoDB::FIELD_UPDATED,
            DatabaseMongoDB::FIELD_UPDATES,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new DatabaseMongoDB($this->client, $json);
    }
}
