<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Databases\Repository;

use Linode\Databases\DatabaseType;
use Linode\Databases\DatabaseTypeRepositoryInterface;
use Linode\Entity;
use Linode\Internal\AbstractRepository;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class DatabaseTypeRepository extends AbstractRepository implements DatabaseTypeRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return 'beta/databases/types';
    }

    protected function getSupportedFields(): array
    {
        return [
            DatabaseType::FIELD_ID,
            DatabaseType::FIELD_LABEL,
            DatabaseType::FIELD_MEMORY,
            DatabaseType::FIELD_DISK,
            DatabaseType::FIELD_VCPUS,
            DatabaseType::FIELD_DEPRECATED,
            DatabaseType::FIELD_CLASS,
            DatabaseType::FIELD_ENGINES,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new DatabaseType($this->client, $json);
    }
}
