<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Databases\Repository;

use Linode\Databases\DatabaseBackup;
use Linode\Databases\DatabaseCredentials;
use Linode\Databases\DatabasePostgreSQL;
use Linode\Databases\DatabasePostgreSQLRepositoryInterface;
use Linode\Databases\DatabaseSSL;
use Linode\Entity;
use Linode\Internal\AbstractRepository;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class DatabasePostgreSQLRepository extends AbstractRepository implements DatabasePostgreSQLRepositoryInterface
{
    public function postDatabasesPostgreSQLInstances(array $parameters = []): DatabasePostgreSQL
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabasePostgreSQL($this->client, $json);
    }

    public function putDatabasesPostgreSQLInstance(int $instanceId, array $parameters = []): DatabasePostgreSQL
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $instanceId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabasePostgreSQL($this->client, $json);
    }

    public function deleteDatabasesPostgreSQLInstance(int $instanceId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $instanceId));
    }

    public function getDatabasesPostgreSQLInstanceBackups(int $instanceId): array
    {
        $response = $this->client->get(sprintf('%s/%s/backups', $this->getBaseUri(), $instanceId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return array_map(fn ($data) => new DatabaseBackup($this->client, $data), $json['data']);
    }

    public function postDatabasesPostgreSQLInstanceBackup(int $instanceId, array $parameters = []): void
    {
        $this->client->post(sprintf('%s/%s/backups', $this->getBaseUri(), $instanceId), $parameters);
    }

    public function getDatabasesPostgreSQLInstanceBackup(int $instanceId, int $backupId): DatabaseBackup
    {
        $response = $this->client->get(sprintf('%s/%s/backups/%s', $this->getBaseUri(), $instanceId, $backupId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabaseBackup($this->client, $json);
    }

    public function deleteDatabasePostgreSQLInstanceBackup(int $instanceId, int $backupId): void
    {
        $this->client->delete(sprintf('%s/%s/backups/%s', $this->getBaseUri(), $instanceId, $backupId));
    }

    public function postDatabasesPostgreSQLInstanceBackupRestore(int $instanceId, int $backupId): void
    {
        $this->client->post(sprintf('%s/%s/backups/%s/restore', $this->getBaseUri(), $instanceId, $backupId));
    }

    public function getDatabasesPostgreSQLInstanceCredentials(int $instanceId): DatabaseCredentials
    {
        $response = $this->client->get(sprintf('%s/%s/credentials', $this->getBaseUri(), $instanceId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabaseCredentials($this->client, $json);
    }

    public function postDatabasesPostgreSQLInstanceCredentialsReset(int $instanceId): void
    {
        $this->client->post(sprintf('%s/%s/credentials/reset', $this->getBaseUri(), $instanceId));
    }

    public function getDatabasesPostgreSQLInstanceSSL(int $instanceId): DatabaseSSL
    {
        $response = $this->client->get(sprintf('%s/%s/ssl', $this->getBaseUri(), $instanceId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new DatabaseSSL($this->client, $json);
    }

    public function postDatabasesPostgreSQLInstancePatch(int $instanceId): void
    {
        $this->client->post(sprintf('%s/%s/patch', $this->getBaseUri(), $instanceId));
    }

    protected function getBaseUri(): string
    {
        return 'beta/databases/postgresql/instances';
    }

    protected function getSupportedFields(): array
    {
        return [
            DatabasePostgreSQL::FIELD_ID,
            DatabasePostgreSQL::FIELD_LABEL,
            DatabasePostgreSQL::FIELD_REGION,
            DatabasePostgreSQL::FIELD_TYPE,
            DatabasePostgreSQL::FIELD_CLUSTER_SIZE,
            DatabasePostgreSQL::FIELD_ENGINE,
            DatabasePostgreSQL::FIELD_VERSION,
            DatabasePostgreSQL::FIELD_TOTAL_DISK_SIZE_GB,
            DatabasePostgreSQL::FIELD_USED_DISK_SIZE_GB,
            DatabasePostgreSQL::FIELD_PORT,
            DatabasePostgreSQL::FIELD_REPLICATION_TYPE,
            DatabasePostgreSQL::FIELD_STATUS,
            DatabasePostgreSQL::FIELD_REPLICATION_COMMIT_TYPE,
            DatabasePostgreSQL::FIELD_ENCRYPTED,
            DatabasePostgreSQL::FIELD_ALLOW_LIST,
            DatabasePostgreSQL::FIELD_HOSTS,
            DatabasePostgreSQL::FIELD_SSL_CONNECTION,
            DatabasePostgreSQL::FIELD_CREATED,
            DatabasePostgreSQL::FIELD_UPDATED,
            DatabasePostgreSQL::FIELD_UPDATES,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new DatabasePostgreSQL($this->client, $json);
    }
}
