<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Volumes\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Volumes\Volume;
use Linode\Volumes\VolumeRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class VolumeRepository extends AbstractRepository implements VolumeRepositoryInterface
{
    public function create(array $parameters): Volume
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Volume($this->client, $json);
    }

    public function update(int $id, array $parameters): Volume
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Volume($this->client, $json);
    }

    public function delete(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    public function clone(int $id, array $parameters): void
    {
        $this->checkParametersSupport($parameters);

        $this->client->post(sprintf('%s/%s/clone', $this->getBaseUri(), $id), $parameters);
    }

    public function resize(int $id, array $parameters): void
    {
        $this->checkParametersSupport($parameters);

        $this->client->post(sprintf('%s/%s/resize', $this->getBaseUri(), $id), $parameters);
    }

    public function attach(int $id, array $parameters): Volume
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post(sprintf('%s/%s/attach', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Volume($this->client, $json);
    }

    public function detach(int $id): void
    {
        $this->client->post(sprintf('%s/%s/detach', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return '/volumes';
    }

    protected function getSupportedFields(): array
    {
        return [
            Volume::FIELD_ID,
            Volume::FIELD_LABEL,
            Volume::FIELD_STATUS,
            Volume::FIELD_SIZE,
            Volume::FIELD_REGION,
            Volume::FIELD_LINODE_ID,
            Volume::FIELD_CONFIG_ID,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Volume($this->client, $json);
    }
}
