<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Tags\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Tags\Tag;
use Linode\Tags\TagRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class TagRepository extends AbstractRepository implements TagRepositoryInterface
{
    public function createTag(array $parameters = []): Tag
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Tag($this->client, $json);
    }

    public function deleteTag(string $tagLabel): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $tagLabel));
    }

    protected function getBaseUri(): string
    {
        return '/tags';
    }

    protected function getSupportedFields(): array
    {
        return [
            Tag::FIELD_LABEL,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Tag($this->client, $json);
    }
}
