<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\ObjectStorage\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\ObjectStorage\ObjectStorageBucket;
use Linode\ObjectStorage\ObjectStorageBucketRepositoryInterface;
use Linode\ObjectStorage\ObjectStorageObject;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ObjectStorageBucketRepository extends AbstractRepository implements ObjectStorageBucketRepositoryInterface
{
    public function createObjectStorageBucket(array $parameters = []): ObjectStorageBucket
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ObjectStorageBucket($this->client, $json);
    }

    public function getObjectStorageBucket(string $clusterId, string $bucket): ObjectStorageBucket
    {
        $response = $this->client->get(sprintf('%s/%s/%s', $this->getBaseUri(), $clusterId, $bucket));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ObjectStorageBucket($this->client, $json);
    }

    public function deleteObjectStorageBucket(string $clusterId, string $bucket): void
    {
        $this->client->delete(sprintf('%s/%s/%s', $this->getBaseUri(), $clusterId, $bucket));
    }

    public function modifyObjectStorageBucketAccess(string $clusterId, string $bucket, array $parameters = []): void
    {
        $this->client->post(sprintf('%s/%s/%s/access', $this->getBaseUri(), $clusterId, $bucket), $parameters);
    }

    public function getObjectStorageBucketContent(string $clusterId, string $bucket): array
    {
        $response = $this->client->get(sprintf('%s/%s/%s/object-list', $this->getBaseUri(), $clusterId, $bucket));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return array_map(fn ($data) => new ObjectStorageObject($this->client, $data), $json['data']);
    }

    public function createObjectStorageObjectURL(string $clusterId, string $bucket, array $parameters = []): string
    {
        $response = $this->client->post(sprintf('%s/%s/%s/object-url', $this->getBaseUri(), $clusterId, $bucket), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return $json['url'];
    }

    public function cancelObjectStorage(): void
    {
        $this->client->post('beta/object-storage/cancel');
    }

    protected function getBaseUri(): string
    {
        return 'beta/object-storage/buckets';
    }

    protected function getSupportedFields(): array
    {
        return [
            ObjectStorageBucket::FIELD_CREATED,
            ObjectStorageBucket::FIELD_CLUSTER,
            ObjectStorageBucket::FIELD_LABEL,
            ObjectStorageBucket::FIELD_HOSTNAME,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ObjectStorageBucket($this->client, $json);
    }
}
