<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\ObjectStorage\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\ObjectStorage\ObjectStorageKey;
use Linode\ObjectStorage\ObjectStorageKeyRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ObjectStorageKeyRepository extends AbstractRepository implements ObjectStorageKeyRepositoryInterface
{
    public function create(array $parameters): ObjectStorageKey
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ObjectStorageKey($this->client, $json);
    }

    public function update(int $id, array $parameters): ObjectStorageKey
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ObjectStorageKey($this->client, $json);
    }

    public function revoke(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return 'beta/object-storage/keys';
    }

    protected function getSupportedFields(): array
    {
        return [
            ObjectStorageKey::FIELD_ID,
            ObjectStorageKey::FIELD_LABEL,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ObjectStorageKey($this->client, $json);
    }
}
