<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Longview;

use Linode\Entity;

/**
 * A LongviewClient is a single monitor set up to track statistics about one of your
 * servers.
 *
 * @property int          $id           This Client's unique ID.
 * @property string       $label        This Client's unique label. This is for display purposes only.
 * @property string       $api_key      The API key for this Client, used when configuring the Longview
 *                                      Client application on your Linode.
 *                                      Returns as `[REDACTED]` if you do not have read-write access to this client.
 * @property string       $install_code The install code for this Client, used when configuring the Longview
 *                                      Client application on your Linode.
 *                                      Returns as `[REDACTED]` if you do not have read-write access to this client.
 * @property string       $created      When this Longview Client was created.
 * @property string       $updated      When this Longview Client was last updated.
 * @property LongviewApps $apps         The apps this Client is monitoring on your Linode. This is configured when you
 *                                      install the Longview Client application, and is present here for information
 *                                      purposes only.
 */
class LongviewClient extends Entity
{
    // Available fields.
    public const FIELD_ID           = 'id';
    public const FIELD_LABEL        = 'label';
    public const FIELD_API_KEY      = 'api_key';
    public const FIELD_INSTALL_CODE = 'install_code';
    public const FIELD_CREATED      = 'created';
    public const FIELD_UPDATED      = 'updated';
    public const FIELD_APPS         = 'apps';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_APPS => new LongviewApps($this->client, $this->data[$name]),
            default          => parent::__get($name),
        };
    }
}
