<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\VPC\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\VPC\VPC;
use Linode\VPC\VPCRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class VPCRepository extends AbstractRepository implements VPCRepositoryInterface
{
    public function createVPC(array $parameters = []): VPC
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new VPC($this->client, $json);
    }

    public function updateVPC(int $vpcId, array $parameters = []): VPC
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $vpcId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new VPC($this->client, $json);
    }

    public function deleteVPC(int $vpcId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $vpcId));
    }

    protected function getBaseUri(): string
    {
        return '/vpcs';
    }

    protected function getSupportedFields(): array
    {
        return [
            VPC::FIELD_ID,
            VPC::FIELD_LABEL,
            VPC::FIELD_DESCRIPTION,
            VPC::FIELD_REGION,
            VPC::FIELD_SUBNETS,
            VPC::FIELD_CREATED,
            VPC::FIELD_UPDATED,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new VPC($this->client, $json);
    }
}
