<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\BetaPrograms\Repository;

use Linode\BetaPrograms\BetaProgram;
use Linode\BetaPrograms\BetaProgramRepositoryInterface;
use Linode\Entity;
use Linode\Internal\AbstractRepository;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class BetaProgramRepository extends AbstractRepository implements BetaProgramRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return '/betas';
    }

    protected function getSupportedFields(): array
    {
        return [
            BetaProgram::FIELD_ID,
            BetaProgram::FIELD_LABEL,
            BetaProgram::FIELD_DESCRIPTION,
            BetaProgram::FIELD_GREENLIGHT_ONLY,
            BetaProgram::FIELD_STARTED,
            BetaProgram::FIELD_ENDED,
            BetaProgram::FIELD_MORE_INFO,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new BetaProgram($this->client, $json);
    }
}
