<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Managed\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Managed\ManagedCredential;
use Linode\Managed\ManagedCredentialRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ManagedCredentialRepository extends AbstractRepository implements ManagedCredentialRepositoryInterface
{
    public function create(array $parameters): ManagedCredential
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ManagedCredential($this->client, $json);
    }

    public function update(int $id, array $parameters): ManagedCredential
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ManagedCredential($this->client, $json);
    }

    public function setLoginInformation(int $id, array $parameters): void
    {
        $this->checkParametersSupport($parameters);

        $this->client->post(sprintf('%s/%s/update', $this->getBaseUri(), $id), $parameters);
    }

    public function delete(int $id): void
    {
        $this->client->post(sprintf('%s/%s/revoke', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return '/managed/credentials';
    }

    protected function getSupportedFields(): array
    {
        return [
            ManagedCredential::FIELD_ID,
            ManagedCredential::FIELD_LABEL,
            ManagedCredential::FIELD_USERNAME,
            ManagedCredential::FIELD_PASSWORD,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ManagedCredential($this->client, $json);
    }
}
