<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Managed\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Managed\ManagedContact;
use Linode\Managed\ManagedContactRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ManagedContactRepository extends AbstractRepository implements ManagedContactRepositoryInterface
{
    public function create(array $parameters): ManagedContact
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ManagedContact($this->client, $json);
    }

    public function update(int $id, array $parameters): ManagedContact
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ManagedContact($this->client, $json);
    }

    public function delete(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return '/managed/contacts';
    }

    protected function getSupportedFields(): array
    {
        return [
            ManagedContact::FIELD_ID,
            ManagedContact::FIELD_NAME,
            ManagedContact::FIELD_EMAIL,
            ManagedContact::FIELD_PHONE,
            ManagedContact::FIELD_GROUP,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ManagedContact($this->client, $json);
    }
}
