<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Managed\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Managed\ManagedLinodeSettings;
use Linode\Managed\ManagedLinodeSettingsRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ManagedLinodeSettingsRepository extends AbstractRepository implements ManagedLinodeSettingsRepositoryInterface
{
    public function update(int $id, array $parameters): ManagedLinodeSettings
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ManagedLinodeSettings($this->client, $json);
    }

    protected function getBaseUri(): string
    {
        return '/managed/linode-settings';
    }

    protected function getSupportedFields(): array
    {
        return [
            ManagedLinodeSettings::FIELD_ID,
            ManagedLinodeSettings::FIELD_LABEL,
            ManagedLinodeSettings::FIELD_GROUP,
            ManagedLinodeSettings::FIELD_SSH,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ManagedLinodeSettings($this->client, $json);
    }
}
