<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Managed\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\Managed\ManagedIssue;
use Linode\Managed\ManagedIssueRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ManagedIssueRepository extends AbstractRepository implements ManagedIssueRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return '/managed/issues';
    }

    protected function getSupportedFields(): array
    {
        return [];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ManagedIssue($this->client, $json);
    }
}
