<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Account\Repository;

use Linode\Account\Invoice;
use Linode\Account\InvoiceRepositoryInterface;
use Linode\Entity;
use Linode\Internal\AbstractRepository;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class InvoiceRepository extends AbstractRepository implements InvoiceRepositoryInterface
{
    protected function getBaseUri(): string
    {
        return '/account/invoices';
    }

    protected function getSupportedFields(): array
    {
        return [
            Invoice::FIELD_ID,
            Invoice::FIELD_DATE,
            Invoice::FIELD_LABEL,
            Invoice::FIELD_SUBTOTAL,
            Invoice::FIELD_TAX,
            Invoice::FIELD_TOTAL,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Invoice($this->client, $json);
    }
}
