<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Account\Repository;

use Linode\Account\ServiceTransfer;
use Linode\Account\ServiceTransferRepositoryInterface;
use Linode\Entity;
use Linode\Internal\AbstractRepository;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ServiceTransferRepository extends AbstractRepository implements ServiceTransferRepositoryInterface
{
    public function createServiceTransfer(array $parameters = []): ServiceTransfer
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ServiceTransfer($this->client, $json);
    }

    public function deleteServiceTransfer(string $token): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $token));
    }

    public function acceptServiceTransfer(string $token): void
    {
        $this->client->post(sprintf('%s/%s/accept', $this->getBaseUri(), $token));
    }

    protected function getBaseUri(): string
    {
        return '/account/service-transfers';
    }

    protected function getSupportedFields(): array
    {
        return [
            ServiceTransfer::FIELD_TOKEN,
            ServiceTransfer::FIELD_STATUS,
            ServiceTransfer::FIELD_EXPIRY,
            ServiceTransfer::FIELD_IS_SENDER,
            ServiceTransfer::FIELD_CREATED,
            ServiceTransfer::FIELD_UPDATED,
            ServiceTransfer::FIELD_ENTITIES,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ServiceTransfer($this->client, $json);
    }
}
