<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Account\Repository;

use Linode\Account\User;
use Linode\Account\UserGrant;
use Linode\Account\UserRepositoryInterface;
use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LinodeClient;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class UserRepository extends AbstractRepository implements UserRepositoryInterface
{
    public function create(array $parameters): User
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new User($this->client, $json);
    }

    public function update(string $username, array $parameters): User
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $username), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new User($this->client, $json);
    }

    public function delete(string $username): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $username));
    }

    public function getUserGrants(string $username): ?UserGrant
    {
        $response = $this->client->get(sprintf('%s/%s/grants', $this->getBaseUri(), $username));

        if (LinodeClient::SUCCESS_NO_CONTENT === $response->getStatusCode()) {
            return null;
        }

        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new UserGrant($this->client, $json);
    }

    public function setUserGrants(string $username, array $parameters): UserGrant
    {
        $response = $this->client->put(sprintf('%s/%s/grants', $this->getBaseUri(), $username), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new UserGrant($this->client, $json);
    }

    protected function getBaseUri(): string
    {
        return '/account/users';
    }

    protected function getSupportedFields(): array
    {
        return [
            User::FIELD_USERNAME,
            User::FIELD_EMAIL,
            User::FIELD_RESTRICTED,
            User::FIELD_SSH_KEYS,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new User($this->client, $json);
    }
}
