<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\NodeBalancers\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\NodeBalancers\NodeBalancer;
use Linode\NodeBalancers\NodeBalancerRepositoryInterface;
use Linode\NodeBalancers\NodeBalancerStats;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class NodeBalancerRepository extends AbstractRepository implements NodeBalancerRepositoryInterface
{
    public function createNodeBalancer(array $parameters = []): NodeBalancer
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NodeBalancer($this->client, $json);
    }

    public function updateNodeBalancer(int $nodeBalancerId, array $parameters = []): NodeBalancer
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $nodeBalancerId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NodeBalancer($this->client, $json);
    }

    public function deleteNodeBalancer(int $nodeBalancerId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $nodeBalancerId));
    }

    public function getNodeBalancerStats(int $nodeBalancerId): NodeBalancerStats
    {
        $response = $this->client->get(sprintf('%s/%s/stats', $this->getBaseUri(), $nodeBalancerId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NodeBalancerStats($this->client, $json);
    }

    protected function getBaseUri(): string
    {
        return '/nodebalancers';
    }

    protected function getSupportedFields(): array
    {
        return [
            NodeBalancer::FIELD_ID,
            NodeBalancer::FIELD_LABEL,
            NodeBalancer::FIELD_REGION,
            NodeBalancer::FIELD_HOSTNAME,
            NodeBalancer::FIELD_IPV4,
            NodeBalancer::FIELD_IPV6,
            NodeBalancer::FIELD_CLIENT_CONN_THROTTLE,
            NodeBalancer::FIELD_CREATED,
            NodeBalancer::FIELD_UPDATED,
            NodeBalancer::FIELD_TAGS,
            NodeBalancer::FIELD_TRANSFER,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new NodeBalancer($this->client, $json);
    }
}
