<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\NodeBalancers\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LinodeClient;
use Linode\NodeBalancers\NodeBalancerNode;
use Linode\NodeBalancers\NodeBalancerNodeRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class NodeBalancerNodeRepository extends AbstractRepository implements NodeBalancerNodeRepositoryInterface
{
    /**
     * @param int $nodeBalancerId The ID of the NodeBalancer to access.
     * @param int $configId       The ID of the NodeBalancer config to access.
     */
    public function __construct(LinodeClient $client, protected int $nodeBalancerId, protected int $configId)
    {
        parent::__construct($client);
    }

    public function createNodeBalancerNode(array $parameters = []): NodeBalancerNode
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NodeBalancerNode($this->client, $json);
    }

    public function updateNodeBalancerNode(int $nodeId, array $parameters = []): NodeBalancerNode
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $nodeId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NodeBalancerNode($this->client, $json);
    }

    public function deleteNodeBalancerConfigNode(int $nodeId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $nodeId));
    }

    protected function getBaseUri(): string
    {
        return sprintf('/nodebalancers/%s/configs/%s/nodes', $this->nodeBalancerId, $this->configId);
    }

    protected function getSupportedFields(): array
    {
        return [
            NodeBalancerNode::FIELD_ID,
            NodeBalancerNode::FIELD_LABEL,
            NodeBalancerNode::FIELD_ADDRESS,
            NodeBalancerNode::FIELD_STATUS,
            NodeBalancerNode::FIELD_WEIGHT,
            NodeBalancerNode::FIELD_MODE,
            NodeBalancerNode::FIELD_NODEBALANCER_ID,
            NodeBalancerNode::FIELD_CONFIG_ID,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new NodeBalancerNode($this->client, $json);
    }
}
