<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\NodeBalancers\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LinodeClient;
use Linode\NodeBalancers\NodeBalancerNode;
use Linode\NodeBalancers\NodeBalancerNodeRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class NodeBalancerNodeRepository extends AbstractRepository implements NodeBalancerNodeRepositoryInterface
{
    /**
     * @param int $nodeBalancerId       The ID of the NodeBalancer we are accessing nodes for
     * @param int $nodeBalancerConfigId The ID of the NodeBalancer config we are accessing nodes for
     */
    public function __construct(LinodeClient $client, protected int $nodeBalancerId, protected int $nodeBalancerConfigId)
    {
        parent::__construct($client);
    }

    public function create(array $parameters): NodeBalancerNode
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NodeBalancerNode($this->client, $json);
    }

    public function update(int $id, array $parameters): NodeBalancerNode
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NodeBalancerNode($this->client, $json);
    }

    public function delete(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return sprintf('/nodebalancers/%s/configs/%s/nodes', $this->nodeBalancerId, $this->nodeBalancerConfigId);
    }

    protected function getSupportedFields(): array
    {
        return [
            NodeBalancerNode::FIELD_ID,
            NodeBalancerNode::FIELD_LABEL,
            NodeBalancerNode::FIELD_ADDRESS,
            NodeBalancerNode::FIELD_STATUS,
            NodeBalancerNode::FIELD_WEIGHT,
            NodeBalancerNode::FIELD_MODE,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new NodeBalancerNode($this->client, $json);
    }
}
