<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\NodeBalancers;

use Linode\Entity;

/**
 * Stats for a NodeBalancer.
 *
 * @property string                $title The title for the statistics generated in this response.
 * @property NodeBalancerStatsData $data  The data returned about this NodeBalancers.
 */
class NodeBalancerStats extends Entity
{
    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            'data'  => new NodeBalancerStatsData($this->client, $this->data[$name]),
            default => parent::__get($name),
        };
    }
}
