<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances;

use Linode\Entity;

/**
 * A dictionary of device disks to use as a device map in a Linode's configuration
 * profile.
 * * An empty device disk dictionary or a dictionary with empty values for device
 * slots is allowed.
 * * If no devices are specified, booting from this configuration will hold until a
 * device exists that allows the boot process to start.
 *
 * @property Device $sda
 * @property Device $sdb
 * @property Device $sdc
 * @property Device $sdd
 * @property Device $sde
 * @property Device $sdf
 * @property Device $sdg
 * @property Device $sdh
 */
class Devices extends Entity
{
    // Available fields.
    public const FIELD_SDA = 'sda';
    public const FIELD_SDB = 'sdb';
    public const FIELD_SDC = 'sdc';
    public const FIELD_SDD = 'sdd';
    public const FIELD_SDE = 'sde';
    public const FIELD_SDF = 'sdf';
    public const FIELD_SDG = 'sdg';
    public const FIELD_SDH = 'sdh';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            default => new Device($this->client, $this->data[$name]),
        };
    }
}
