<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances;

use Linode\Entity;
use Linode\Networking\IPAddress;
use Linode\Networking\IPAddressPrivate;

/**
 * Information about this Linode's IPv4 addresses.
 *
 * @property IPAddress[]        $public   A list of public IP Address objects belonging to this Linode.
 * @property IPAddressPrivate[] $private  A list of private IP Address objects belonging to this Linode.
 * @property IPAddress[]        $shared   A list of shared IP Address objects assigned to this Linode.
 * @property IPAddress[]        $reserved A list of reserved IP Address objects belonging to this Linode.
 */
class IPv4Information extends Entity
{
    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): ?array
    {
        return match ($name) {
            'private' => array_map(fn ($data) => new IPAddressPrivate($this->client, $data), $this->data[$name]),
            default   => array_map(fn ($data) => new IPAddress($this->client, $data), $this->data[$name]),
        };
    }
}
