<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances;

use Linode\Entity;
use Linode\Networking\IPAddress;
use Linode\Networking\IPv6Pool;

/**
 * @property IPAddress $link_local
 * @property IPAddress $slaac
 * @property IPv6Pool  $global
 */
class IPv6Information extends Entity
{
    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            'link_local' => new IPAddress($this->client, $this->data['link_local']),
            'slaac'      => new IPAddress($this->client, $this->data['slaac']),
            'global'     => new IPv6Pool($this->client, $this->data['global']),
            default      => parent::__get($name),
        };
    }
}
