<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances;

use Linode\Entity;

/**
 * CPU, IO, IPv4, and IPv6 statistics. Graph data, if available, is in "[timestamp,
 * reading]" array format. Timestamp is a UNIX timestamp in EST.
 *
 * @property string       $title The title for this data set.
 * @property float[][]    $cpu   Percentage of CPU used.
 * @property IOStats      $io    Input/Output statistics.
 * @property NetworkStats $netv4 IPv4 statistics.
 * @property NetworkStats $netv6 IPv6 statistics.
 */
class LinodeStats extends Entity
{
    // Available fields.
    public const FIELD_TITLE = 'title';
    public const FIELD_CPU   = 'cpu';
    public const FIELD_IO    = 'io';
    public const FIELD_NETV4 = 'netv4';
    public const FIELD_NETV6 = 'netv6';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_IO    => new IOStats($this->client, $this->data[$name]),
            self::FIELD_NETV4,
            self::FIELD_NETV6 => new NetworkStats($this->client, $this->data[$name]),
            default           => parent::__get($name),
        };
    }
}
