<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances;

use Linode\Entity;

/**
 * Information about this Linode's backups status.
 *
 * @property bool                 $enabled  If this Linode has the Backup service enabled.
 * @property LinodeBackupSchedule $schedule Information about this Linode's backups schedule.
 */
class LinodeBackups extends Entity
{
    // Available fields.
    public const FIELD_SCHEDULE = 'schedule';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_SCHEDULE => new LinodeBackupSchedule($this->client, $this->data[self::FIELD_SCHEDULE]),
            default              => parent::__get($name),
        };
    }
}
