<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances;

use Linode\Entity;

/**
 * Requested Linode's networking configuration.
 *
 * @property IPv4Information $ipv4 Information about this Linode's IPv4 addresses.
 * @property IPv6Information $ipv6 Information about this Linode's IPv6 addresses.
 */
class NetworkInformation extends Entity
{
    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            'ipv4'  => new IPv4Information($this->client, $this->data[$name]),
            'ipv6'  => new IPv6Information($this->client, $this->data[$name]),
            default => parent::__get($name),
        };
    }
}
