<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Networking;

use Linode\Entity;

/**
 * A Rule can have up to 255 addresses or networks listed across its IPv4 and IPv6
 * arrays. A network and a single IP are treated as equivalent when accounting for
 * this limit.
 *
 * @property FirewallRuleConfig[] $inbound
 * @property FirewallRuleConfig[] $outbound
 */
class FirewallRules extends Entity
{
    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): array
    {
        return array_map(fn ($data) => new FirewallRuleConfig($this->client, $data), $this->data[$name]);
    }
}
