<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Networking;

use Linode\Entity;
use Linode\Networking\Repository\FirewallDevicesRepository;

/**
 * A resource that controls incoming and outgoing network traffic to a compute
 * service. Only one enabled Firewall can be attached to a particular service at any
 * given time. Create a Firewall Device to assign a Firewall to a service. Currently,
 * Firewalls can assigned to Linode compute instances and NodeBalancers.
 *
 * @property int                                $id      The Firewall's unique ID.
 * @property string                             $label   The Firewall's label, for display purposes only.
 *                                                       Firewall labels have the following constraints:
 *                                                       * Must begin and end with an alphanumeric character.
 *                                                       * May only consist of alphanumeric characters, hyphens (`-`), underscores (`_`)
 *                                                       or periods (`.`).
 *                                                       * Cannot have two hyphens (`--`), underscores (`__`) or periods (`..`) in a row.
 *                                                       * Must be between 3 and 32 characters.
 *                                                       * Must be unique.
 * @property string                             $status  The status of this Firewall.
 *                                                       * When a Firewall is first created its status is `enabled`.
 *                                                       * Use the Update Firewall endpoint to set a Firewall's status to `enabled` or
 *                                                       `disabled`.
 *                                                       * Use the Delete Firewall endpoint to delete a Firewall.
 * @property string                             $created When this Firewall was created.
 * @property string                             $updated When this Firewall was last updated.
 * @property FirewallRules                      $rules   The inbound and outbound access rules to apply to the Firewall.
 *                                                       A Firewall may have up to 25 rules across its inbound and outbound rulesets.
 *                                                       Multiple rules are applied in order. If two rules conflict, the first rule takes
 *                                                       precedence. For example, if the first rule accepts inbound traffic from an
 *                                                       address, and the second rule drops inbound traffic the same address, the first
 *                                                       rule applies and inbound traffic from that address is accepted.
 * @property string[]                           $tags    An array of tags applied to this object. Tags are for organizational purposes
 *                                                       only.
 * @property FirewallDevicesRepositoryInterface $devices Firewall devices.
 */
class Firewall extends Entity
{
    // Available fields.
    public const FIELD_ID      = 'id';
    public const FIELD_LABEL   = 'label';
    public const FIELD_STATUS  = 'status';
    public const FIELD_CREATED = 'created';
    public const FIELD_UPDATED = 'updated';
    public const FIELD_RULES   = 'rules';
    public const FIELD_TAGS    = 'tags';

    // Extra fields for POST/PUT requests.
    public const FIELD_DEVICES  = 'devices';
    public const FIELD_INBOUND  = 'inbound';
    public const FIELD_OUTBOUND = 'outbound';

    // `FIELD_STATUS` values.
    public const STATUS_ENABLED  = 'enabled';
    public const STATUS_DISABLED = 'disabled';
    public const STATUS_DELETED  = 'deleted';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_RULES   => new FirewallRules($this->client, $this->data[$name]),
            self::FIELD_DEVICES => new FirewallDevicesRepository($this->client, $this->id),
            default             => parent::__get($name),
        };
    }
}
