<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LKE;

use Linode\Entity;
use Linode\LKE\Repository\LKENodePoolRepository;

/**
 * A Kubernetes cluster.
 *
 * @property int                            $id          This Kubernetes cluster's unique ID.
 * @property string                         $label       This Kubernetes cluster's unique label for display purposes only. If no label is
 *                                                       provided, one will be assigned automatically.
 * @property string                         $region      This Kubernetes cluster's location.
 * @property string                         $created     When this Kubernetes cluster was created.
 * @property string                         $updated     When this Kubernetes cluster was updated.
 * @property string                         $k8s_version The desired Kubernetes version for this Kubernetes cluster in the format of
 *                                                       <major>.<minor>, and the latest supported patch version will be deployed.
 * @property string[]                       $tags        An array of tags applied to the Kubernetes cluster. Tags are for organizational
 *                                                       purposes only.
 * @property LKENodePoolRepositoryInterface $nodePools   Node pools.
 */
class LKECluster extends Entity
{
    // Available fields.
    public const FIELD_ID          = 'id';
    public const FIELD_LABEL       = 'label';
    public const FIELD_REGION      = 'region';
    public const FIELD_CREATED     = 'created';
    public const FIELD_UPDATED     = 'updated';
    public const FIELD_K8S_VERSION = 'k8s_version';
    public const FIELD_TAGS        = 'tags';

    // Extra fields for POST/PUT requests.
    public const FIELD_NODE_POOLS = 'node_pools';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            'nodePools' => new LKENodePoolRepository($this->client, $this->id),
            default     => parent::__get($name),
        };
    }
}
