<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Account;

use Linode\Entity;
use Linode\Linode\LinodeEntity;

/**
 * Information about maintenance affecting an entity.
 *
 * @property string       $type   The type of maintenance.
 * @property string       $status The maintenance status.
 * @property string       $reason The reason maintenance is being performed.
 * @property string       $when   When the maintenance will begin.
 *                                Filterable with the following parameters:
 *                                * A single value in date-time string format ("%Y-%m-%dT%H:%M:%S"), which returns
 *                                only matches to that value.
 *                                * A dictionary containing pairs of inequality operator string keys ("+or", "+gt",
 *                                "+gte", "+lt", "+lte",
 *                                or "+neq") and single date-time string format values ("%Y-%m-%dT%H:%M:%S"). "+or"
 *                                accepts an array of values that
 *                                may consist of single date-time strings or dictionaries of inequality operator
 *                                pairs.
 * @property LinodeEntity $entity The entity being affected by maintenance.
 */
class Maintenance extends Entity
{
    // Available fields.
    public const FIELD_TYPE   = 'type';
    public const FIELD_STATUS = 'status';
    public const FIELD_REASON = 'reason';
    public const FIELD_WHEN   = 'when';
    public const FIELD_ENTITY = 'entity';

    // `FIELD_TYPE` values.
    public const TYPE_REBOOT         = 'reboot';
    public const TYPE_COLD_MIGRATION = 'cold_migration';
    public const TYPE_LIVE_MIGRATION = 'live_migration';

    // `FIELD_STATUS` values.
    public const STATUS_PENDING = 'pending';
    public const STATUS_STARTED = 'started';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_ENTITY => new LinodeEntity($this->client, $this->data[$name]),
            default            => parent::__get($name),
        };
    }
}
