<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Account;

use Linode\Entity;

/**
 * An object representing your network utilization for the current month, in
 * Gigabytes.
 *
 * Certain Regions have separate utilization quotas and rates. For Region-specific
 * network utilization data, see `region_transfers`.
 *
 * @property int              $quota            The amount of network usage allowed this billing cycle.
 * @property int              $used             The amount of network usage you have used this billing cycle.
 * @property int              $billable         The amount of your transfer pool that is billable this billing cycle.
 * @property RegionTransfer[] $region_transfers
 */
class Transfer extends Entity
{
    // Available fields.
    public const FIELD_QUOTA            = 'quota';
    public const FIELD_USED             = 'used';
    public const FIELD_BILLABLE         = 'billable';
    public const FIELD_REGION_TRANSFERS = 'region_transfers';

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_REGION_TRANSFERS => array_map(fn ($data) => new RegionTransfer($this->client, $data), $this->data[$name]),
            default                      => parent::__get($name),
        };
    }
}
