<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Databases;

use Linode\Entity;
use Linode\Linode\Price;

/**
 * @property int   $quantity The number of nodes for the Managed Database cluster for this subscription tier.
 * @property Price $price    Cost in US dollars, broken down into hourly and monthly charges.
 */
class DatabaseTypeEngine extends Entity
{
    // Available fields.
    public const FIELD_QUANTITY = 'quantity';
    public const FIELD_PRICE    = 'price';

    // `FIELD_QUANTITY` values.
    public const QUANTITY_1 = 1;
    public const QUANTITY_2 = 2;
    public const QUANTITY_3 = 3;

    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return match ($name) {
            self::FIELD_PRICE => new Price($this->client, $this->data[$name]),
            default           => parent::__get($name),
        };
    }
}
