<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\Databases;

use Linode\Entity;

/**
 * @property DatabaseTypeEngine[] $mysql      Pricing details for MySQL Managed Databases.
 * @property DatabaseTypeEngine[] $postgresql Pricing details for PostgreSQL Managed Databases.
 * @property DatabaseTypeEngine[] $mongodb    Pricing details for MongoDB Managed Databases.
 */
class DatabaseEngines extends Entity
{
    /**
     * @codeCoverageIgnore This method was autogenerated.
     */
    public function __get(string $name): mixed
    {
        return array_map(fn ($data) => new DatabaseTypeEngine($this->client, $data), $this->data[$name]);
    }
}
