<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LinodeClient;
use Linode\LinodeInstances\ConfigurationProfile;
use Linode\LinodeInstances\ConfigurationProfileRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class ConfigurationProfileRepository extends AbstractRepository implements ConfigurationProfileRepositoryInterface
{
    /**
     * @param int $linodeId The ID of the Linode whose Configuration profile to look up
     */
    public function __construct(LinodeClient $client, protected int $linodeId)
    {
        parent::__construct($client);
    }

    public function create(array $parameters): ConfigurationProfile
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ConfigurationProfile($this->client, $json);
    }

    public function update(int $id, array $parameters): ConfigurationProfile
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new ConfigurationProfile($this->client, $json);
    }

    public function delete(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    protected function getBaseUri(): string
    {
        return sprintf('/linode/instances/%s/configs', $this->linodeId);
    }

    protected function getSupportedFields(): array
    {
        return [
            ConfigurationProfile::FIELD_ID,
            ConfigurationProfile::FIELD_LABEL,
            ConfigurationProfile::FIELD_KERNEL,
            ConfigurationProfile::FIELD_COMMENTS,
            ConfigurationProfile::FIELD_MEMORY_LIMIT,
            ConfigurationProfile::FIELD_RUN_LEVEL,
            ConfigurationProfile::FIELD_VIRT_MODE,
            ConfigurationProfile::FIELD_HELPERS,
            ConfigurationProfile::FIELD_DEVICES,
            ConfigurationProfile::FIELD_ROOT_DEVICE,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new ConfigurationProfile($this->client, $json);
    }
}
