<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LinodeClient;
use Linode\LinodeInstances\Disk;
use Linode\LinodeInstances\DiskRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class DiskRepository extends AbstractRepository implements DiskRepositoryInterface
{
    /**
     * @param int $linodeId The ID of the Linode whose Disk to look up
     */
    public function __construct(LinodeClient $client, protected int $linodeId)
    {
        parent::__construct($client);
    }

    public function create(array $parameters): Disk
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Disk($this->client, $json);
    }

    public function update(int $id, array $parameters): Disk
    {
        $this->checkParametersSupport($parameters);

        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Disk($this->client, $json);
    }

    public function delete(int $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    public function clone(int $id): Disk
    {
        $response = $this->client->post(sprintf('%s/%s/clone', $this->getBaseUri(), $id));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Disk($this->client, $json);
    }

    public function resize(int $id, int $size): void
    {
        $parameters = [
            'size' => $size,
        ];

        $this->client->post(sprintf('%s/%s/resize', $this->getBaseUri(), $id), $parameters);
    }

    public function resetPassword(int $id, string $password): void
    {
        $parameters = [
            'password' => $password,
        ];

        $this->client->post(sprintf('%s/%s/password', $this->getBaseUri(), $id), $parameters);
    }

    protected function getBaseUri(): string
    {
        return sprintf('/linode/instances/%s/disks', $this->linodeId);
    }

    protected function getSupportedFields(): array
    {
        return [
            Disk::FIELD_ID,
            Disk::FIELD_LABEL,
            Disk::FIELD_STATUS,
            Disk::FIELD_SIZE,
            Disk::FIELD_FILESYSTEM,
            Disk::FIELD_CREATED,
            Disk::FIELD_UPDATED,
            Disk::FIELD_READ_ONLY,
            Disk::FIELD_IMAGE,
            Disk::FIELD_ROOT_PASS,
            Disk::FIELD_AUTHORIZED_KEYS,
            Disk::FIELD_AUTHORIZED_USERS,
            Disk::FIELD_STACKSCRIPT_ID,
            Disk::FIELD_STACKSCRIPT_DATA,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Disk($this->client, $json);
    }
}
