<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LinodeClient;
use Linode\LinodeInstances\Disk;
use Linode\LinodeInstances\DiskRepositoryInterface;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class DiskRepository extends AbstractRepository implements DiskRepositoryInterface
{
    /**
     * @param int $linodeId ID of the Linode to look up.
     */
    public function __construct(LinodeClient $client, protected int $linodeId)
    {
        parent::__construct($client);
    }

    public function addLinodeDisk(array $parameters = []): Disk
    {
        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Disk($this->client, $json);
    }

    public function updateDisk(int $diskId, array $parameters = []): Disk
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $diskId), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Disk($this->client, $json);
    }

    public function deleteDisk(int $diskId): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $diskId));
    }

    public function cloneLinodeDisk(int $diskId): Disk
    {
        $response = $this->client->post(sprintf('%s/%s/clone', $this->getBaseUri(), $diskId));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new Disk($this->client, $json);
    }

    public function resetDiskPassword(int $diskId, string $password): void
    {
        $parameters = [
            'password' => $password,
        ];

        $this->client->post(sprintf('%s/%s/password', $this->getBaseUri(), $diskId), $parameters);
    }

    public function resizeDisk(int $diskId, int $size): void
    {
        $parameters = [
            'size' => $size,
        ];

        $this->client->post(sprintf('%s/%s/resize', $this->getBaseUri(), $diskId), $parameters);
    }

    protected function getBaseUri(): string
    {
        return sprintf('/linode/instances/%s/disks', $this->linodeId);
    }

    protected function getSupportedFields(): array
    {
        return [
            Disk::FIELD_ID,
            Disk::FIELD_LABEL,
            Disk::FIELD_STATUS,
            Disk::FIELD_SIZE,
            Disk::FIELD_FILESYSTEM,
            Disk::FIELD_CREATED,
            Disk::FIELD_UPDATED,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Disk($this->client, $json);
    }
}
