<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances\Repository;

use Linode\LinodeClient;
use Linode\LinodeInstances\LinodeNetworkRepositoryInterface;
use Linode\LinodeInstances\NetworkInformation;
use Linode\Networking\IPAddress;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class LinodeNetworkRepository implements LinodeNetworkRepositoryInterface
{
    /**
     * @param int $linodeId ID of the Linode to look up
     */
    public function __construct(protected LinodeClient $client, protected int $linodeId) {}

    public function getNetworkInformation(): NetworkInformation
    {
        $response = $this->client->get($this->getBaseUri());
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new NetworkInformation($this->client, $json);
    }

    public function find(string $id): IPAddress
    {
        $response = $this->client->get(sprintf('%s/%s', $this->getBaseUri(), $id));
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new IPAddress($this->client, $json);
    }

    public function allocate(bool $public, string $type = IPAddress::TYPE_IP4): IPAddress
    {
        $parameters = [
            'public'    => $public,
            'type'      => $type,
        ];

        $response = $this->client->post($this->getBaseUri(), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new IPAddress($this->client, $json);
    }

    public function update(string $id, array $parameters): IPAddress
    {
        $response = $this->client->put(sprintf('%s/%s', $this->getBaseUri(), $id), $parameters);
        $contents = $response->getBody()->getContents();
        $json     = json_decode($contents, true);

        return new IPAddress($this->client, $json);
    }

    public function delete(string $id): void
    {
        $this->client->delete(sprintf('%s/%s', $this->getBaseUri(), $id));
    }

    /**
     * Returns base URI to the repository-specific API.
     */
    protected function getBaseUri(): string
    {
        return sprintf('/linode/instances/%s/ips', $this->linodeId);
    }
}
