<?php

// ---------------------------------------------------------------------
//
//  Copyright (C) 2018-2024 Artem Rodygin
//
//  You should have received a copy of the MIT License along with
//  this file. If not, see <https://opensource.org/licenses/MIT>.
//
// ---------------------------------------------------------------------

namespace Linode\LinodeInstances\Repository;

use Linode\Entity;
use Linode\Internal\AbstractRepository;
use Linode\LinodeClient;
use Linode\LinodeInstances\LinodeVolumeRepositoryInterface;
use Linode\Volumes\Volume;

/**
 * @codeCoverageIgnore This class was autogenerated.
 */
class LinodeVolumeRepository extends AbstractRepository implements LinodeVolumeRepositoryInterface
{
    /**
     * @param int $linodeId ID of the Linode to look up
     */
    public function __construct(LinodeClient $client, protected int $linodeId)
    {
        parent::__construct($client);
    }

    protected function getBaseUri(): string
    {
        return sprintf('/linode/instances/%s/volumes', $this->linodeId);
    }

    protected function getSupportedFields(): array
    {
        return [
            Volume::FIELD_ID,
            Volume::FIELD_LABEL,
            Volume::FIELD_STATUS,
            Volume::FIELD_SIZE,
            Volume::FIELD_REGION,
            Volume::FIELD_LINODE_ID,
        ];
    }

    protected function jsonToEntity(array $json): Entity
    {
        return new Volume($this->client, $json);
    }
}
